stages:
  - test
  - build
  - deploy

test-job:
  stage: test
  image: maven:4.0.0-rc-5-amazoncorretto-25
  script:
    - mvn test
  #only:
  #  - main
  #  - develop
  #  - merge requests

build-job:
  stage: build
  script:
    - docker build --network=host -t my-backend .
  #only:
  #  - main

deploy-job:
  stage: deploy
  image: docker/compose:2.20.2
  services:
    - name: docker:24.0.2-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker info
    - docker compose up -d
