stages:
  - test
  - build
  - deploy

test-job:
  stage: test
  image: maven:4.0.0-rc-5-amazoncorretto-25
  script:
    - mvn test
  #only:
  #  - main
  #  - develop
  #  - merge requests

build-job:
  stage: build
  script:
    - docker build --network=host -t my-backend .
  #only:
  #  - main

deploy-job:
  stage: deploy
  image: docker:24.0.2
  script:
    - docker compose up -d
  #only:
  #  - main
