name: vSrok
services:
  backend:
    image: leoagf/devback:1.14
    depends_on:
      - db
      - nginx
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - app-volume:/static

  db:
    image: leoagf/bd:1.0
    restart: unless-stopped
    volumes:
      - ./src/main/resources/bd:/var/lib/postgresql/18
    ports:
      - "1234:5432"

  nginx:
    image: nginx:latest
    ports:
      - "1235:80"
    volumes:
      - app-volume:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  app-volume: