name: vSrok
services:

  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "1234:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres

  db_dev:
    image: leoagf/devbd:1.9
    #image: postgres
    restart: unless-stopped
    ports:
      - "1234:5432"
    #environment:
    #  POSTGRES_USERNAME: postgres
    #  POSTGRES_PASSWORD: root
    #  POSTGRES_DB: postgres
    #volumes:
    #  - ./src/main/resources/bd:/var/lib/postgresql/18

  nginx:
    image: nginx:latest
    ports:
      - "1235:80"
    volumes:
      - ./src/main/resources/static:/usr/share/nginx/html:ro
    restart: unless-stopped
